### ISSUE TITLE
Tracking the International Space Station (ISS) Using NASA API, Carto DB, and then maybe D3

### ISSUE THREAD

**Issue by radhikapc** [jsoma/playfair-projects#249]
Being a Space enthusiast, I have been following the development of ISS since it's conception. I get an alert in my Inbox when it crosses the Santa Clara - Sunnyvale area ! I am following the humans on board on ISS via twitter feeds. Well, after learning to play around with API, then Carto, I thought why don't I try plotting its movement across the sky for a day. In fact, ISS makes 16 rotation around earth daily. To get an interesting animation of the movement of ISS, I collected data by using the http://open-notify.org APIs (thanks Stephen for helping me fix the issues !). 
I initially tried a simple plotting on Carto, but the image didn't look that attractive ! Yes, I did a spatial-join of a shape file of the globe (thanks Nicky for directing me to the right one!) and the CSV file I have created .
![capture](https://cloud.githubusercontent.com/assets/3285001/17839838/e299919e-67c2-11e6-8566-6401aea42ff9.JPG)

The image captures the movement for a day, implies 16 rotation around earth. 

Thanks to Soma, who suggested to try Torque feature on Carto. Now it looks better, but I need to make lots of modification to make it look pretty. I wish to do it on D3. 

![capture](https://cloud.githubusercontent.com/assets/3285001/17839856/64228de2-67c3-11e6-9df4-34b3444dee6b.JPG)

My pitch was (use the number): # 249

-# Pitch issue checklist
- [x] My pitch issue has `[Pitch]` in the title
- [x] My pitch issue has `[Data request]` in the title if I need additional data
- [x] My pitch issue links to my data set
- [x] My pitch issue explains what I'd like to explore in the data set
- [ ] My pitch issue includes multiple possible headlines
- [ ] My pitch issue includes any links/images I'm using as inspiration
- [ ] I have received two comments of peer feedback on my pitch issue

**Comment by playfairbot** [comment]
Hi there, I'm the Playfair Bot!

Would you mind **posting the appropriate checklist** in the main body of your issue? You might have posted it as the first comment, but it turns out it works *way better* in the actual body of the issue - just go up to the veeery top right and click the **pencil icon** to edit. You'll probably want to edit the comment to copy the checklist, then edit the original issue to paste it in.

Thanks! :pray:
